Update patch set 8
Patch Set 8:

> Patch Set 8: Code-Review-1
> 
> please fix config-api UT
> 
> 
> Captured traceback:
> ~~~~~~~~~~~~~~~~~~~
>     Traceback (most recent call last):
>       File "/root/work/build/debug/config/api-server/vnc_cfg_api_server/tests/in_place_upgrade/test_r2002.py", line 1691, in test_virtual_network_create
>         obj = self.set_properties(VirtualNetwork, prop_map)
>       File "/root/work/build/debug/config/api-server/vnc_cfg_api_server/tests/in_place_upgrade/test_case.py", line 91, in set_properties
>         obj.resource_type))
>     Exception: Properties nod defined in prop_map: mac_ip_learning_enable for object: virtual-network

I have raised another review for the same that fixes the issue since the file is in contrail-controller git repo.

https://review.opencontrail.org/c/Juniper/contrail-controller/+/60963

Patch-set: 8
Reviewer: Gerrit User 473 <473@c72cd27d-1743-4a55-84a4-cd13b8400c52>